<!-- ########## Footer ########## -->
      <footer>
            <article>
                  <h3 id="footer_h3">Swinburne University of Technology &#169; | Assignment 2 </h3>
                  <ul id="contacts">
                        <li id="email_icon">&#9993;</li>
                        <li><a href="mailto:101934317@student.swin.edu.au"> Joy </a></li>
                        <li><a href="mailto:101533031@student.swim.edu.au"> Nelson </a></li>
                        <li><a href="mailto:103844052@student.swin.edu.au"> Minh </a></li>
                        <li><a href="mailto:103177240@student.swin.edu.a"> Tom </a></li>
                        <li><a href="mailto:102608927@student.swin.edu.au"> Uzman </a></li>
                  </ul>
            </article>

      </footer>