<header>
	<nav class="navbar">
	<div class="navbar__container">
		  
		<a href="index.php" id="navbar__logo">Voice Technology</a>
		  
		<div class="navbar__toggle" id="mobile-menu">
			<span class="bar"></span> <span class="bar"></span>
			<span class="bar"></span>
		 </div>
			<ul class="navbar__menu">
				<li class="navbar__item">
					<a href="index.php" class="navbar__links">Home</a>
				</li>
				<li class="navbar__item">
					<a href="topic.php" class="navbar__links">Topic</a>
				</li>
				<li class="navbar__item">
					<a href="quiz.php" class="navbar__links">Quiz</a>
				</li>
				<li class="navbar__item">
					<a href="enhancements.html" class="navbar__links">Enhancements</a>
				</li>
				<li class="navbar__item">
					<a href="manage.php" class="navbar__links">Manage</a>
				</li>
			</ul>
	</div>
	</nav>
</header>